language: node_js
node_js:
  - node
branches:
  only:
    - master
install:
  - npm install
script:
  - npm run test
  - npm run build
before_deploy:
  - pwd
deploy:
  provider: npm
  edge: true
  skip_cleanup: true
  email: "$NPM_EMAIL"
  api_key: "$NPM_TOKEN"
  on:
    tags: false
    repo: Linkontoask/v-easy-components
