language: node_js
node_js:
  - node
before_install:
  - openssl aes-256-cbc -K $encrypted_cefdef829077_key -iv $encrypted_cefdef829077_iv
    -in id_rsa.enc -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa
install:
  - npm install
script:
  - npm run test
  - npm run build
  - npm run build:docs
after_success:
  - sh build/docs.sh
deploy:
  provider: npm
  edge: true
  skip_cleanup: true
  email: "$NPM_EMAIL"
  api_key: "$NPM_TOKEN"
  on:
    tags: false
    branch: master
    repo: Linkontoask/v-easy-components
