language: node_js
node_js:
  - node
before_install:
  - openssl aes-256-cbc -K $encrypted_3ad82f112fed_key -iv $encrypted_3ad82f112fed_iv
    -in id_rsa.enc -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa
install:
  - yarn
script:
  - yarn test
  - yarn build
after_success:
  - sh build/docs.sh
deploy:
  provider: npm
  edge: true
  cleanup: true
  email: "$NPM_EMAIL"
  api_token: "$NPM_TOKEN"
  on:
    tags: false
    branch: master
    repo: Linkontoask/v-easy-components
notifications:
  slack:
    if: branch = docs
  email:
    on_success: always
    recipients:
      - linkorgs@163.com
