language: node_js
node_js:
- node
install:
- npm install
script:
- npm run build
deploy:
  provider: npm
  email: linkorgs@163.com
  api_key:
    secure: MJcFOyEzkYcCeck6LrUXBp1AMc5zMvinRmDcT+iCX6spTPYTW2PStHJOBvFxgPo6y4mqjQFfUOy8YTcYwXa83mXllxC6i4miZgoNvJyBz3qiQaP1J5DcTCZA55nOSw1mFh9uCJNhWjp97yDjd41Z++fFnPCwzVtOH4nvtIbvJ1obIbF9xpgGTviPicnh7Re8o/r2IEeB0XffjkXB7ajH7jKvtMihsPUQnbx/7GrkjXeV0QgfxfGnhbFPXIPTSmvoPQSPMafWRZCcDpwDhXTfhf5FWIy2fIOYpAvLoVEGfnD9DQjv9jaMHDnfhYF4vB94tayUa6orFjQXEhm4KoYdI1kdrj0Z7w1lIq58e8hyeel7DbZGPsY61oj14TS+RS/aJndPmwPublIDM2XbCpbMOgwrqLNNOa5ipyOJ2/r7SvOTymxG51BAMsSdR1YiYVmFETYxQj6E4jcRGA7KXv+vWf+aHOVADcdL26/KQJGsWs8vsc+Tq4hCxoNiqEmP2xOhbeBqP+qfrm2hVgJWyXEK4I+P+ZMv4YJwEuMAeBAhSWrzyu8RxWlap7zTV7WcMqjv0577caalh397oABhOZiE+Lj52lUfohZzu8rqHL5MZyJUFUX9lvS046dQ8YFxVsu87JTUlOib/pniiOVZA+0SM84aicfX9HnDddJnk92OLvg=
  on:
    tags: true
    repo: Linkontoask/v-easy-components
